/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KitchenRouteImport } from './routes/_kitchen'
import { Route as KitchenIndexRouteImport } from './routes/_kitchen.index'
import { Route as KitchenFormsRouteImport } from './routes/_kitchen.forms'
import { Route as KitchenTodosRouteImport } from './routes/_kitchen.todos'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSplatRouteImport } from './routes/docs.$'

const KitchenRoute = KitchenRouteImport.update({
  id: '/_kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenIndexRoute = KitchenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KitchenRoute,
} as any)
const KitchenFormsRoute = KitchenFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => KitchenRoute,
} as any)
const KitchenTodosRoute = KitchenTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => KitchenRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof KitchenIndexRoute
  '/forms': typeof KitchenFormsRoute
  '/todos': typeof KitchenTodosRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/forms': typeof KitchenFormsRoute
  '/todos': typeof KitchenTodosRoute
  '/docs/$': typeof DocsSplatRoute
  '/': typeof KitchenIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_kitchen': typeof KitchenRouteWithChildren
  '/_kitchen/forms': typeof KitchenFormsRoute
  '/_kitchen/todos': typeof KitchenTodosRoute
  '/docs/$': typeof DocsSplatRoute
  '/_kitchen/': typeof KitchenIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forms' | '/todos' | '/docs/$' | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/forms' | '/todos' | '/docs/$' | '/' | '/docs'
  id:
    | '__root__'
    | '/_kitchen'
    | '/_kitchen/forms'
    | '/_kitchen/todos'
    | '/docs/$'
    | '/_kitchen/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  KitchenRoute: typeof KitchenRouteWithChildren
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_kitchen': {
      id: '/_kitchen'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_kitchen/': {
      id: '/_kitchen/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof KitchenIndexRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/_kitchen/forms': {
      id: '/_kitchen/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof KitchenFormsRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/_kitchen/todos': {
      id: '/_kitchen/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof KitchenTodosRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KitchenRouteChildren {
  KitchenFormsRoute: typeof KitchenFormsRoute
  KitchenTodosRoute: typeof KitchenTodosRoute
  KitchenIndexRoute: typeof KitchenIndexRoute
}

const KitchenRouteChildren: KitchenRouteChildren = {
  KitchenFormsRoute: KitchenFormsRoute,
  KitchenTodosRoute: KitchenTodosRoute,
  KitchenIndexRoute: KitchenIndexRoute,
}

const KitchenRouteWithChildren =
  KitchenRoute._addFileChildren(KitchenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  KitchenRoute: KitchenRouteWithChildren,
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
