/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KitchenRouteImport } from './routes/_kitchen'
import { Route as KitchenIndexRouteImport } from './routes/_kitchen.index'
import { Route as KitchenTodosRouteImport } from './routes/_kitchen.todos'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as KitchenBlocksDataTableRouteImport } from './routes/_kitchen.blocks.data-table'
import { Route as KitchenBlocksDescriptionsRouteImport } from './routes/_kitchen.blocks.descriptions'
import { Route as KitchenBlocksFilterToolbarRouteImport } from './routes/_kitchen.blocks.filter-toolbar'
import { Route as KitchenBlocksFormDialogRouteImport } from './routes/_kitchen.blocks.form-dialog'
import { Route as KitchenBlocksFormDrawerRouteImport } from './routes/_kitchen.blocks.form-drawer'
import { Route as KitchenBlocksFormsRouteImport } from './routes/_kitchen.blocks.forms'
import { Route as KitchenBlocksPageContainerRouteImport } from './routes/_kitchen.blocks.page-container'
import { Route as KitchenBlocksStepFormRouteImport } from './routes/_kitchen.blocks.step-form'

const KitchenRoute = KitchenRouteImport.update({
  id: '/_kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenIndexRoute = KitchenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KitchenRoute,
} as any)
const KitchenTodosRoute = KitchenTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => KitchenRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenBlocksDataTableRoute = KitchenBlocksDataTableRouteImport.update({
  id: '/blocks/data-table',
  path: '/blocks/data-table',
  getParentRoute: () => KitchenRoute,
} as any)
const KitchenBlocksDescriptionsRoute =
  KitchenBlocksDescriptionsRouteImport.update({
    id: '/blocks/descriptions',
    path: '/blocks/descriptions',
    getParentRoute: () => KitchenRoute,
  } as any)
const KitchenBlocksFilterToolbarRoute =
  KitchenBlocksFilterToolbarRouteImport.update({
    id: '/blocks/filter-toolbar',
    path: '/blocks/filter-toolbar',
    getParentRoute: () => KitchenRoute,
  } as any)
const KitchenBlocksFormDialogRoute = KitchenBlocksFormDialogRouteImport.update({
  id: '/blocks/form-dialog',
  path: '/blocks/form-dialog',
  getParentRoute: () => KitchenRoute,
} as any)
const KitchenBlocksFormDrawerRoute = KitchenBlocksFormDrawerRouteImport.update({
  id: '/blocks/form-drawer',
  path: '/blocks/form-drawer',
  getParentRoute: () => KitchenRoute,
} as any)
const KitchenBlocksFormsRoute = KitchenBlocksFormsRouteImport.update({
  id: '/blocks/forms',
  path: '/blocks/forms',
  getParentRoute: () => KitchenRoute,
} as any)
const KitchenBlocksPageContainerRoute =
  KitchenBlocksPageContainerRouteImport.update({
    id: '/blocks/page-container',
    path: '/blocks/page-container',
    getParentRoute: () => KitchenRoute,
  } as any)
const KitchenBlocksStepFormRoute = KitchenBlocksStepFormRouteImport.update({
  id: '/blocks/step-form',
  path: '/blocks/step-form',
  getParentRoute: () => KitchenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof KitchenIndexRoute
  '/todos': typeof KitchenTodosRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/blocks/data-table': typeof KitchenBlocksDataTableRoute
  '/blocks/descriptions': typeof KitchenBlocksDescriptionsRoute
  '/blocks/filter-toolbar': typeof KitchenBlocksFilterToolbarRoute
  '/blocks/form-dialog': typeof KitchenBlocksFormDialogRoute
  '/blocks/form-drawer': typeof KitchenBlocksFormDrawerRoute
  '/blocks/forms': typeof KitchenBlocksFormsRoute
  '/blocks/page-container': typeof KitchenBlocksPageContainerRoute
  '/blocks/step-form': typeof KitchenBlocksStepFormRoute
}
export interface FileRoutesByTo {
  '/todos': typeof KitchenTodosRoute
  '/docs/$': typeof DocsSplatRoute
  '/': typeof KitchenIndexRoute
  '/docs': typeof DocsIndexRoute
  '/blocks/data-table': typeof KitchenBlocksDataTableRoute
  '/blocks/descriptions': typeof KitchenBlocksDescriptionsRoute
  '/blocks/filter-toolbar': typeof KitchenBlocksFilterToolbarRoute
  '/blocks/form-dialog': typeof KitchenBlocksFormDialogRoute
  '/blocks/form-drawer': typeof KitchenBlocksFormDrawerRoute
  '/blocks/forms': typeof KitchenBlocksFormsRoute
  '/blocks/page-container': typeof KitchenBlocksPageContainerRoute
  '/blocks/step-form': typeof KitchenBlocksStepFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_kitchen': typeof KitchenRouteWithChildren
  '/_kitchen/todos': typeof KitchenTodosRoute
  '/docs/$': typeof DocsSplatRoute
  '/_kitchen/': typeof KitchenIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/_kitchen/blocks/data-table': typeof KitchenBlocksDataTableRoute
  '/_kitchen/blocks/descriptions': typeof KitchenBlocksDescriptionsRoute
  '/_kitchen/blocks/filter-toolbar': typeof KitchenBlocksFilterToolbarRoute
  '/_kitchen/blocks/form-dialog': typeof KitchenBlocksFormDialogRoute
  '/_kitchen/blocks/form-drawer': typeof KitchenBlocksFormDrawerRoute
  '/_kitchen/blocks/forms': typeof KitchenBlocksFormsRoute
  '/_kitchen/blocks/page-container': typeof KitchenBlocksPageContainerRoute
  '/_kitchen/blocks/step-form': typeof KitchenBlocksStepFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/todos'
    | '/docs/$'
    | '/docs/'
    | '/blocks/data-table'
    | '/blocks/descriptions'
    | '/blocks/filter-toolbar'
    | '/blocks/form-dialog'
    | '/blocks/form-drawer'
    | '/blocks/forms'
    | '/blocks/page-container'
    | '/blocks/step-form'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/todos'
    | '/docs/$'
    | '/'
    | '/docs'
    | '/blocks/data-table'
    | '/blocks/descriptions'
    | '/blocks/filter-toolbar'
    | '/blocks/form-dialog'
    | '/blocks/form-drawer'
    | '/blocks/forms'
    | '/blocks/page-container'
    | '/blocks/step-form'
  id:
    | '__root__'
    | '/_kitchen'
    | '/_kitchen/todos'
    | '/docs/$'
    | '/_kitchen/'
    | '/docs/'
    | '/_kitchen/blocks/data-table'
    | '/_kitchen/blocks/descriptions'
    | '/_kitchen/blocks/filter-toolbar'
    | '/_kitchen/blocks/form-dialog'
    | '/_kitchen/blocks/form-drawer'
    | '/_kitchen/blocks/forms'
    | '/_kitchen/blocks/page-container'
    | '/_kitchen/blocks/step-form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  KitchenRoute: typeof KitchenRouteWithChildren
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_kitchen': {
      id: '/_kitchen'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_kitchen/': {
      id: '/_kitchen/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof KitchenIndexRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/_kitchen/todos': {
      id: '/_kitchen/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof KitchenTodosRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_kitchen/blocks/data-table': {
      id: '/_kitchen/blocks/data-table'
      path: '/blocks/data-table'
      fullPath: '/blocks/data-table'
      preLoaderRoute: typeof KitchenBlocksDataTableRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/_kitchen/blocks/descriptions': {
      id: '/_kitchen/blocks/descriptions'
      path: '/blocks/descriptions'
      fullPath: '/blocks/descriptions'
      preLoaderRoute: typeof KitchenBlocksDescriptionsRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/_kitchen/blocks/filter-toolbar': {
      id: '/_kitchen/blocks/filter-toolbar'
      path: '/blocks/filter-toolbar'
      fullPath: '/blocks/filter-toolbar'
      preLoaderRoute: typeof KitchenBlocksFilterToolbarRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/_kitchen/blocks/form-dialog': {
      id: '/_kitchen/blocks/form-dialog'
      path: '/blocks/form-dialog'
      fullPath: '/blocks/form-dialog'
      preLoaderRoute: typeof KitchenBlocksFormDialogRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/_kitchen/blocks/form-drawer': {
      id: '/_kitchen/blocks/form-drawer'
      path: '/blocks/form-drawer'
      fullPath: '/blocks/form-drawer'
      preLoaderRoute: typeof KitchenBlocksFormDrawerRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/_kitchen/blocks/forms': {
      id: '/_kitchen/blocks/forms'
      path: '/blocks/forms'
      fullPath: '/blocks/forms'
      preLoaderRoute: typeof KitchenBlocksFormsRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/_kitchen/blocks/page-container': {
      id: '/_kitchen/blocks/page-container'
      path: '/blocks/page-container'
      fullPath: '/blocks/page-container'
      preLoaderRoute: typeof KitchenBlocksPageContainerRouteImport
      parentRoute: typeof KitchenRoute
    }
    '/_kitchen/blocks/step-form': {
      id: '/_kitchen/blocks/step-form'
      path: '/blocks/step-form'
      fullPath: '/blocks/step-form'
      preLoaderRoute: typeof KitchenBlocksStepFormRouteImport
      parentRoute: typeof KitchenRoute
    }
  }
}

interface KitchenRouteChildren {
  KitchenTodosRoute: typeof KitchenTodosRoute
  KitchenIndexRoute: typeof KitchenIndexRoute
  KitchenBlocksDataTableRoute: typeof KitchenBlocksDataTableRoute
  KitchenBlocksDescriptionsRoute: typeof KitchenBlocksDescriptionsRoute
  KitchenBlocksFilterToolbarRoute: typeof KitchenBlocksFilterToolbarRoute
  KitchenBlocksFormDialogRoute: typeof KitchenBlocksFormDialogRoute
  KitchenBlocksFormDrawerRoute: typeof KitchenBlocksFormDrawerRoute
  KitchenBlocksFormsRoute: typeof KitchenBlocksFormsRoute
  KitchenBlocksPageContainerRoute: typeof KitchenBlocksPageContainerRoute
  KitchenBlocksStepFormRoute: typeof KitchenBlocksStepFormRoute
}

const KitchenRouteChildren: KitchenRouteChildren = {
  KitchenTodosRoute: KitchenTodosRoute,
  KitchenIndexRoute: KitchenIndexRoute,
  KitchenBlocksDataTableRoute: KitchenBlocksDataTableRoute,
  KitchenBlocksDescriptionsRoute: KitchenBlocksDescriptionsRoute,
  KitchenBlocksFilterToolbarRoute: KitchenBlocksFilterToolbarRoute,
  KitchenBlocksFormDialogRoute: KitchenBlocksFormDialogRoute,
  KitchenBlocksFormDrawerRoute: KitchenBlocksFormDrawerRoute,
  KitchenBlocksFormsRoute: KitchenBlocksFormsRoute,
  KitchenBlocksPageContainerRoute: KitchenBlocksPageContainerRoute,
  KitchenBlocksStepFormRoute: KitchenBlocksStepFormRoute,
}

const KitchenRouteWithChildren =
  KitchenRoute._addFileChildren(KitchenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  KitchenRoute: KitchenRouteWithChildren,
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
