export function getNativewindTemplateFiles(name, _options = {}) {
  const files = new Map();

  files.set('package.json', JSON.stringify({
    name,
    private: true,
    version: '0.1.0',
    scripts: {
      start: 'expo start',
      android: 'expo start --android',
      ios: 'expo start --ios',
      web: 'expo start --web',
      lint: 'oxlint'
    },
    dependencies: {
      expo: '~52.0.0',
      react: '19.2.6',
      'react-native': '0.81.4',
      'nativewind': '5.0.0-rc.0',
      'react-native-css': '3.1.0-rc.0',
      'react-native-reanimated': '^4.5.1',
      'react-native-safe-area-context': '^5.0.0',
      'react-native-worklets': '^0.10.1',
      'expo-system-ui': '~4.0.0'
    },
    devDependencies: {
      '@tailwindcss/postcss': '4.1.12',
      lightningcss: '1.30.1',
      postcss: '^8.4.49',
      tailwindcss: '4.1.12',
      typescript: '^5.8.3',
      '@types/react': '^19.0.0'
    },
    overrides: {
      lightningcss: '1.30.1'
    },
    pnpm: {
      overrides: {
        lightningcss: '1.30.1'
      }
    }
  }, null, 2) + '\n');

  files.set('postcss.config.mjs', `export default {
  plugins: {
    '@tailwindcss/postcss': {},
  },
};
`);

  files.set('metro.config.js', `const { getDefaultConfig } = require('expo/metro-config');
const { withNativewind } = require('nativewind/metro');

/**
 * Metro configuration for React Native Expo with Nativewind v5 and Tailwind CSS v4.
 * @type {import('expo/metro-config').MetroConfig}
 */
const config = getDefaultConfig(__dirname);

module.exports = withNativewind(config);
`);

  files.set('tsconfig.json', JSON.stringify({
    compilerOptions: {
      strict: true,
      paths: {
        '@/*': ['./src/*']
      }
    },
    include: ['src', 'App.tsx', 'nativewind-env.d.ts']
  }, null, 2) + '\n');

  files.set('app.json', JSON.stringify({
    expo: {
      name,
      slug: name,
      version: '1.0.0',
      orientation: 'portrait',
      userInterfaceStyle: 'automatic',
      newArchEnabled: true
    }
  }, null, 2) + '\n');

  files.set('nativewind-env.d.ts', `/// <reference types="react-native-css/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by react-native-css.
export {};
`);

  files.set('src/index.css', `@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css";

@import "nativewind/theme";

@theme inline {
  --color-primary: #007aff;
  --color-primary-foreground: #ffffff;
  --color-secondary: #2c2c2e;
  --color-secondary-foreground: #f5f5f7;
  --color-destructive: #ff453a;
  --color-destructive-foreground: #ffffff;
  --color-card: #1c1c1e;
  --color-card-foreground: #f5f5f7;
  --color-border: rgba(255, 255, 255, 0.12);
}
`);

  files.set('App.tsx', `import './src/index.css';
import React from 'react';
import { View, Text } from 'react-native';

export default function App() {
  return (
    <View className="flex-1 bg-slate-950 items-center justify-center p-6">
      <View className="max-w-md w-full items-center space-y-4 rounded-xl border border-slate-800 bg-slate-900 p-8">
        <Text className="text-3xl font-bold text-slate-50">${name}</Text>
        <Text className="text-slate-400 text-sm text-center">
          Universal Apps starter powered by Nativewind v5 RC0 and Tailwind CSS v4.
        </Text>
      </View>
    </View>
  );
}
`);

  return files;
}
